/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
/*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Bot Builder',
      //items: ['Chatbots', 'Intents', 'FAQs', 'Entities', 'Dialogue Manager'],
    },
     {
      type: 'category',
      label: 'Live Bots',
     // items: ['Deployments', 'Analytics', 'Knowledge Base'],
    },
     {
      type: 'category',
      label: 'Help Desk',
      //items: ['Live Chats', 'Archived Chats', 'Queue', 'Contact List', 'Queue Management','Template Messaging', 'Proactive Messaging','Reporting'],
    },
    {
      type: 'category',
      label: 'Settings',
      //items: ['User Management', 'General Settings'],
    },
    {
      type: 'category',
      label: 'Speech Tools',
      //items: ['Text To Speech', 'Speech To Test', 'Voice Verification'],
    },
    {
      type: 'category',
      label: 'Tutorials',
     // items: ['Tutorial 1', 'Tutorial 2', 'Tutorial 3'],
    },
  ],
 */
};
